package de.karl_der_iii.economymc.service;

import java.util.HashMap;
import java.util.Map;

public final class LanguageManager {
    private static final Map<String, Map<String, String>> LANG = new HashMap<>();
    private static final Map<String, String> LANGUAGE_NAMES = new HashMap<>();

    static {
        LANGUAGE_NAMES.put("de_de", "Deutsch");
        LANGUAGE_NAMES.put("en_us", "English");
        LANGUAGE_NAMES.put("pl_pl", "Polski");
        LANGUAGE_NAMES.put("fr_fr", "Français");
        LANGUAGE_NAMES.put("es_es", "Español");
        LANGUAGE_NAMES.put("pt_br", "Português");
        LANGUAGE_NAMES.put("ru_ru", "Русский");
        LANGUAGE_NAMES.put("tr_tr", "Türkçe");
        LANGUAGE_NAMES.put("zh_cn", "中文");
        LANGUAGE_NAMES.put("ja_jp", "日本語");

        Map<String, String> en = new HashMap<>();

        en.put("cmd.only_players", "Only players can use this command.");

        en.put("common.close", "§cClose");
        en.put("common.back", "§cBack");
        en.put("common.next", "§7Next Page");
        en.put("common.previous", "§7Previous Page");
        en.put("common.confirm", "§aConfirm");
        en.put("common.cancel", "§cCancel");
        en.put("common.create", "§aCreate");
        en.put("common.edit", "§eEdit");
        en.put("common.price", "§6Price");
        en.put("common.description", "§7Description");
        en.put("common.status", "§7Status");
        en.put("common.page", "§7Page ");
        en.put("common.seller", "§7Seller");
        en.put("common.amount", "§7Amount");
        en.put("common.click_to_view", "§7Click to view");
        en.put("common.publish", "§bPublish");
        en.put("common.sell", "§aSell");
        en.put("common.treasury", "Treasury");
        en.put("common.location", "§7Location");
        en.put("common.chunks", "§7Chunks");

        en.put("help.header", "§6EconomyMC Commands");
        en.put("help.plots", "§e/ec §7- opens the main menu");
        en.put("help.shop", "§7Shop is in the main menu");
        en.put("help.jobs", "§7Jobs are in the main menu");
        en.put("help.checks", "§7Checks are in the main menu");
        en.put("help.history", "§7History is in the main menu");
        en.put("help.bank", "§7Bank is in the main menu");
        en.put("help.daily", "§7Daily reward is in the main menu");
        en.put("help.pay", "§7Pay is in the main menu");
        en.put("help.servermode", "§7Server mode is in the main menu");
        en.put("help.adminmode", "§7Admin mode is in the main menu");
        en.put("help.admin", "§7Admin functions are in the main menu");
        en.put("help.language", "§7Languages: German, English, Polish, French, Spanish, Portuguese, Russian, Turkish, Chinese, Japanese");

        en.put("msg.shop_disabled", "§cShop is disabled by admin.");
        en.put("msg.jobs_disabled", "§cJobs are disabled by admin.");
        en.put("msg.checks_disabled", "§cChecks are disabled by admin.");
        en.put("msg.servermode_disabled", "§cServer mode is disabled by admin.");

        en.put("menu.player.balance", "§6Balance: $%d");
        en.put("menu.player.normal", "§7Normal Credits: %d");
        en.put("menu.player.capital", "§7Capital Credits: %d");

        en.put("main.menu.title", "EconomyMC");
        en.put("main.plots", "§aPlots");
        en.put("main.shop", "§eShop");
        en.put("main.jobs", "§bJobs");
        en.put("main.checks", "§dChecks");
        en.put("main.bank", "§6Bank");
        en.put("main.history", "§7History");
        en.put("main.daily", "§aDaily Reward");
        en.put("main.pay", "§6Pay");
        en.put("main.servermode", "§cServer Mode");
        en.put("main.servermode.disabled", "§8Server Mode Disabled");
        en.put("main.adminmode", "§4Admin Mode");
        en.put("main.disabled.shop", "§8Shop Disabled");
        en.put("main.disabled.jobs", "§8Jobs Disabled");
        en.put("main.disabled.checks", "§8Checks Disabled");
        en.put("main.disabled.servermode", "§8Server Mode Disabled");

        en.put("admin.mode.title", "EconomyMC Admin Mode");
        en.put("admin.jobs", "Jobs");
        en.put("admin.checks", "Checks");
        en.put("admin.shop", "Shop");
        en.put("admin.plot_market", "Plot Market");
        en.put("admin.server_mode", "Server Mode");
        en.put("admin.min_tax", "Minimum Tax");
        en.put("admin.min_overdue", "Minimum Overdue Penalty");
        en.put("admin.min_cancel", "Minimum Cancel Penalty");
        en.put("admin.language", "Language");
        en.put("admin.language.previous", "§ePrevious Language");
        en.put("admin.language.next", "§eNext Language");
        en.put("admin.language.toggle", "§eChange Language");
        en.put("admin.on", "ON");
        en.put("admin.off", "OFF");
        en.put("admin.auto", "Auto");
        en.put("admin.manual", "Manual");

        en.put("plots.menu.title", "EconomyMC Plots");
        en.put("plots.position.capital", "§6Current Position: Capital Zone");
        en.put("plots.position.normal", "§7Current Position: Normal Zone");
        en.put("plots.buy.normal", "§eBuy Normal Claim Credits");
        en.put("plots.buy.capital", "§6Buy Capital Claim Credits");
        en.put("plots.create.sale", "§aCreate Sale Listing");
        en.put("plots.market", "§3Market Listings");
        en.put("plots.mine", "§bMy Plots");
        en.put("plots.sales", "§dMy Sales");
        en.put("plots.history", "§aOpen History");
        en.put("plots.connector", "§7OpenPants Connect");
        en.put("plots.buy.normal.fail", "§cYou do not have enough money for a normal claim credit.");
        en.put("plots.buy.normal.ok", "§aBought 1 normal claim credit.");
        en.put("plots.buy.capital.fail", "§cYou do not have enough money for a capital claim credit.");
        en.put("plots.buy.capital.ok", "§aBought 1 capital claim credit.");

        en.put("market.menu.title", "EconomyMC Market");
        en.put("market.back", "§cBack");

        en.put("myplots.menu.title", "My Plots");
        en.put("myplots.info", "§7Click a plot to create a sale draft");
        en.put("myplots.already_listed", "§cThis plot is already listed in the market.");
        en.put("myplots.already_draft", "§cThis plot already has a sale draft.");
        en.put("myplots.edit_later", "Edit later");

        en.put("mysales.menu.title", "My Sales");

        en.put("listing.menu.title", "EconomyMC Listing");
        en.put("listing.missing", "§cListing no longer exists");
        en.put("listing.buy", "§aBuy");
        en.put("listing.buy.own", "§cYou cannot buy your own listing.");
        en.put("listing.not.enough", "§cYou do not have enough money.");
        en.put("listing.not.exists", "§cListing no longer exists.");
        en.put("listing.price", "§6Price: $%d");
        en.put("listing.description", "§7Description: %s");
        en.put("listing.location", "§7Location: %s");
        en.put("listing.building", "§7Built on Plot: %s");
        en.put("listing.reason", "§7Price Justification: %s");
        en.put("listing.chunks", "§7Chunks: %d");

        en.put("sale.menu.title", "EconomyMC Create Sale Listing");
        en.put("sale.no_draft", "§cNo sale draft selected");
        en.put("sale.plot", "§bPlot: ");
        en.put("sale.chunks", " Chunks");
        en.put("sale.set_price", "§eSet Price");
        en.put("sale.set_description", "§7Set Description");
        en.put("sale.set_built", "§7Set Built On Plot");
        en.put("sale.set_justification", "§7Set Price Justification");
        en.put("sale.negotiable", "§aNegotiable");
        en.put("sale.fixed", "§6Fixed Price");
        en.put("sale.publish", "§bPublish Listing");
        en.put("sale.location", "§7Location: ");
        en.put("sale.clear_draft", "§cClear Draft");
        en.put("sale.already_listed", "§cThis plot is already listed in the market.");
        en.put("sale.published", "§aListing published.");
        en.put("sale.cleared", "§aSale draft cleared.");
        en.put("sale.selected_capital", "§6Selected Capital Plot");
        en.put("sale.selected_plot", "§7Selected Plot");

        en.put("shop.menu.title", "EconomyMC Shop");
        en.put("shop.sell.title", "EconomyMC Sell Item");
        en.put("shop.detail.title", "EconomyMC Shop Detail");
        en.put("shop.detail.not_found", "§cListing not found");
        en.put("shop.detail.info", "§bListing Info");
        en.put("shop.detail.buy", "§aBuy");
        en.put("shop.bundle", "§dShop Bundle");
        en.put("shop.base_price", "§6Base Price: $");
        en.put("shop.tax", "§cTax: $");
        en.put("shop.total", "§aTotal: $");
        en.put("shop.stacks_inside", "§7Stacks inside: ");
        en.put("shop.total_items", "§7Total items: ");
        en.put("shop.and_more", "§8...and more");
        en.put("shop.sell.set_price", "§eSet Price");
        en.put("shop.sell.publish", "§aPublish");
        en.put("shop.sell.put_items_first", "§cPut items in first.");
        en.put("shop.sell.published", "§aShop listing published.");
        en.put("shop.input.enter_price", "§eEnter the shop price in chat now.");
        en.put("shop.input.no_draft", "§cNo shop draft selected.");
        en.put("shop.input.price_positive", "§cPrice must be above 0.");
        en.put("shop.input.price_set", "§aShop price set to $");
        en.put("shop.input.invalid_number", "§cThat is not a valid number.");
        en.put("shop.listing_missing", "Listing no longer exists");
        en.put("shop.not_enough_money", "§cYou do not have enough money.");
        en.put("shop.buy", "§aBuy");
        en.put("shop.withdraw", "§cWithdraw Listing");
        en.put("shop.withdrawn", "§aListing withdrawn.");

        en.put("jobs.menu.title", "EconomyMC Jobs");
        en.put("jobs.server.title", "EconomyMC Server Jobs");
        en.put("job.detail.title", "EconomyMC Job Details");
        en.put("jobs.add", "§aAdd Job");
        en.put("jobs.create_hint", "§7Create jobs in the correct menu");
        en.put("jobs.status.open", "§aOpen");
        en.put("jobs.status.opens_at", "§eOpens ");
        en.put("jobs.status.in_progress", "§6In Progress: ");
        en.put("jobs.status.completed", "§bCompleted");
        en.put("jobs.status.confirmed", "§aConfirmed");
        en.put("jobs.status.cancelled", "§cCancelled");
        en.put("jobs.status.failed", "§4Failed");
        en.put("jobs.reward", "§6Reward: $");
        en.put("jobs.created_by", "§7Created by: ");
        en.put("jobs.description", "§7Description: ");
        en.put("jobs.due_in", "§7Due in: ");
        en.put("jobs.day_suffix", " day(s)");
        en.put("jobs.current_payout", "§7Current payout: $");
        en.put("jobs.unavailable", "§cJob no longer available");
        en.put("jobs.accept", "§aAccept Job");
        en.put("jobs.accept_server", "§aAccept Server Job");
        en.put("jobs.available_at", "§eAvailable at ");
        en.put("jobs.withdraw", "§cWithdraw Job");
        en.put("jobs.mark_completed", "§bMark as Completed");
        en.put("jobs.cancel_job", "§cCancel Job");
        en.put("jobs.in_progress_by", "§7In Progress by ");
        en.put("jobs.confirm_job", "§aConfirm Job");
        en.put("jobs.waiting_confirmation", "§7Waiting for confirmation");

        en.put("jobs.input.title", "§eEnter the job title in chat now.");
        en.put("jobs.input.server_title", "§eEnter the server job title in chat now.");
        en.put("jobs.input.description", "§eEnter the job description in chat now.");
        en.put("jobs.input.reward", "§eEnter the reward amount in chat now.");
        en.put("jobs.input.due_days", "§eEnter the due time in full days now.");
        en.put("jobs.input.invalid_number", "§cThat is not a valid number.");
        en.put("jobs.input.reward_positive", "§cReward must be above 0.");
        en.put("jobs.input.days_positive", "§cDue days must be above 0.");
        en.put("jobs.input.treasury_missing", "§cThe treasury does not have enough money for this server job.");
        en.put("jobs.input.player_missing_money", "§cYou do not have enough money to create this job.");
        en.put("jobs.input.created", "§aJob created.");

        en.put("jobs.error.accept_yet", "§cThis job cannot be accepted yet.");
        en.put("jobs.error.not_open", "§cThis job is no longer open.");
        en.put("jobs.error.own_job", "§cYou cannot accept your own job.");
        en.put("jobs.error.withdraw", "§cCould not withdraw job.");
        en.put("jobs.error.complete", "§cCould not mark job as completed.");
        en.put("jobs.error.confirm", "§cCould not confirm job.");
        en.put("jobs.error.cancel", "§cCould not cancel job.");

        en.put("jobs.msg.accepted", "§aYou accepted the job.");
        en.put("jobs.msg.accepted_server", "§aYou accepted the server job.");
        en.put("jobs.msg.withdrawn", "§aJob withdrawn.");
        en.put("jobs.msg.withdrawn_server", "§aServer job withdrawn.");
        en.put("jobs.msg.completed", "§aJob marked as completed.");
        en.put("jobs.msg.confirmed", "§aJob confirmed.");
        en.put("jobs.msg.cancelled_penalty", "§cJob cancelled. Penalty: $");

        en.put("checks.menu.title", "EconomyMC Checks");
        en.put("check.redeem.title", "EconomyMC Redeem Check");
        en.put("checks.create", "§aCreate Check");
        en.put("checks.creator", "§eCreator: ");
        en.put("checks.amount", "§6Amount: $");
        en.put("checks.redeem", "§aRedeem");
        en.put("checks.redeemed", "§7Already redeemed");
        en.put("checks.not_found", "§cCheck not found");
        en.put("checks.no_longer", "§cThis check can no longer be redeemed.");
        en.put("checks.entry", "%sCheck $%d - %s");

        en.put("checks.input.amount", "§eEnter the check amount in chat now.");
        en.put("checks.input.code", "§eEnter the check code in chat now.");
        en.put("checks.input.invalid_number", "§cThat is not a valid number.");
        en.put("checks.input.amount_positive", "§cAmount must be above 0.");
        en.put("checks.input.not_enough", "§cYou do not have enough money.");
        en.put("checks.input.created", "§aCheck created.");
        en.put("checks.input.invalid_code", "§cInvalid code or check already redeemed.");
        en.put("checks.input.redeemed_success", "§aCheck redeemed successfully.");

        en.put("history.title", "EconomyMC History");
        en.put("history.empty", "§7No entries yet.");
        en.put("history.mine", "§bMy History");
        en.put("history.treasury", "§6Treasury History");
        en.put("history.open", "§aOpen History");
        en.put("history.pay.sent", "§aPay to %s: $%d");
        en.put("history.pay.received", "§aPay from %s: $%d");
        en.put("history.daily", "§eDaily reward: $%d");

        en.put("bank.title", "EconomyMC Bank");
        en.put("bank.loan_id", "Loan ID");
        en.put("bank.invalid_target", "§cUnknown target player.");
        en.put("bank.not_enough_money", "§cYou do not have enough money.");
        en.put("bank.not_found", "§cLoan not found.");
        en.put("bank.request.created", "§aLoan request created.");
        en.put("bank.offer.created", "§aLoan offer created.");
        en.put("bank.accepted", "§aLoan accepted.");
        en.put("bank.repaid", "§aLoan repaid.");
        en.put("bank.target.server", "Server");
        en.put("bank.target.player", "Player");
        en.put("bank.target.all", "All Players");
        en.put("bank.command.request", "Create Loan Request");
        en.put("bank.command.offer", "Create Loan Offer");
        en.put("bank.command.accept", "Accept Loan");
        en.put("bank.command.repay", "Repay Loan");
        en.put("bank.command.list", "Open loans");
        en.put("bank.detail.title", "EconomyMC Loan Details");
        en.put("bank.detail.info_hint", "§7Open a loan to see details");
        en.put("bank.detail.borrower", "§7Borrower: ");
        en.put("bank.detail.lender", "§7Lender: ");
        en.put("bank.detail.amount", "§6Amount: $");
        en.put("bank.detail.status", "§7Status: ");

        en.put("pay.menu.title", "EconomyMC Pay");
        en.put("pay.menu.player", "§ePay %s");
        en.put("pay.menu.info", "§7Select a player");
        en.put("pay.menu.enter_amount", "§eEnter the amount for %s in chat now.");
        en.put("pay.invalid_number", "§cThat is not a valid amount.");
        en.put("pay.target_offline", "§cThat player is no longer online.");
        en.put("pay.known_or_treasury", "§cOnly known players or Treasury can receive money.");
        en.put("pay.self", "§cYou cannot pay yourself.");
        en.put("pay.not_enough", "§cYou do not have enough money.");
        en.put("pay.sent", "§aYou paid $%d to %s.");
        en.put("pay.received", "§aYou received $%d from %s.");

        en.put("daily.already", "§cDaily already claimed for today. Come back in %dh %dm.");
        en.put("daily.claimed", "§aYou claimed your daily $100.");

        en.put("server.mode.title", "EconomyMC Server Mode");
        en.put("server.tax_minus", "§cTax -1%");
        en.put("server.tax_rate", "§7Tax Rate: ");
        en.put("server.tax_plus", "§aTax +1%");
        en.put("server.auto_tax", "Auto Tax");
        en.put("server.overdue_minus", "§cOverdue -1%");
        en.put("server.overdue_penalty", "§7Overdue Penalty: ");
        en.put("server.overdue_plus", "§aOverdue +1%");
        en.put("server.cancel_minus", "§cCancel -1%");
        en.put("server.cancel_penalty", "§7Cancel Penalty: ");
        en.put("server.cancel_plus", "§aCancel +1%");
        en.put("server.days_minus", "§cDays -1");
        en.put("server.max_overdue_days", "§7Max Overdue Days: ");
        en.put("server.days_plus", "§aDays +1");
        en.put("server.start_hour_minus", "§cStart Hour -1");
        en.put("server.job_open_hour", "§7Job Open Hour: ");
        en.put("server.start_hour_plus", "§aStart Hour +1");
        en.put("server.create_job", "§aCreate Server Job");
        en.put("server.open_jobs", "§bOpen Server Jobs");
        en.put("server.treasury_balance", "§6Treasury: $");

        LANG.put("en_us", en);

        Map<String, String> de = new HashMap<>(en);
        de.put("cmd.only_players", "Nur Spieler können diesen Befehl benutzen.");
        de.put("common.close", "§cSchließen");
        de.put("common.back", "§cZurück");
        de.put("common.next", "§7Nächste Seite");
        de.put("common.previous", "§7Vorherige Seite");
        de.put("common.confirm", "§aBestätigen");
        de.put("common.cancel", "§cAbbrechen");
        de.put("common.create", "§aErstellen");
        de.put("common.edit", "§eBearbeiten");
        de.put("common.price", "§6Preis");
        de.put("common.description", "§7Beschreibung");
        de.put("common.status", "§7Status");
        de.put("common.page", "§7Seite ");
        de.put("common.seller", "§7Verkäufer");
        de.put("common.amount", "§7Betrag");
        de.put("common.click_to_view", "§7Zum Anzeigen klicken");
        de.put("common.publish", "§bVeröffentlichen");
        de.put("common.sell", "§aVerkaufen");
        de.put("common.location", "§7Ort");
        de.put("common.chunks", "§7Chunks");

        de.put("help.header", "§6EconomyMC Befehle");
        de.put("help.plots", "§e/ec §7- öffnet das Hauptmenü");
        de.put("help.shop", "§7Shop ist im Hauptmenü");
        de.put("help.jobs", "§7Jobs sind im Hauptmenü");
        de.put("help.checks", "§7Checks sind im Hauptmenü");
        de.put("help.history", "§7Verlauf ist im Hauptmenü");
        de.put("help.bank", "§7Bank ist im Hauptmenü");
        de.put("help.daily", "§7Tägliche Belohnung ist im Hauptmenü");
        de.put("help.pay", "§7Bezahlen ist im Hauptmenü");
        de.put("help.servermode", "§7Servermodus ist im Hauptmenü");
        de.put("help.adminmode", "§7Adminmodus ist im Hauptmenü");
        de.put("help.admin", "§7Adminfunktionen sind im Hauptmenü");
        de.put("help.language", "§7Sprachen: Deutsch, Englisch, Polnisch, Französisch, Spanisch, Portugiesisch, Russisch, Türkisch, Chinesisch, Japanisch");

        de.put("msg.shop_disabled", "§cShop ist vom Admin deaktiviert.");
        de.put("msg.jobs_disabled", "§cJobs sind vom Admin deaktiviert.");
        de.put("msg.checks_disabled", "§cChecks sind vom Admin deaktiviert.");
        de.put("msg.servermode_disabled", "§cServer-Modus ist vom Admin deaktiviert.");

        de.put("menu.player.balance", "§6Kontostand: $%d");
        de.put("menu.player.normal", "§7Normale Credits: %d");
        de.put("menu.player.capital", "§7Hauptstadt-Credits: %d");

        de.put("main.plots", "§aGrundstücke");
        de.put("main.history", "§7Verlauf");
        de.put("main.daily", "§aTägliche Belohnung");
        de.put("main.pay", "§6Bezahlen");
        de.put("main.servermode", "§cServermodus");
        de.put("main.servermode.disabled", "§8Servermodus deaktiviert");
        de.put("main.adminmode", "§4Adminmodus");
        de.put("main.disabled.shop", "§8Shop deaktiviert");
        de.put("main.disabled.jobs", "§8Jobs deaktiviert");
        de.put("main.disabled.checks", "§8Checks deaktiviert");
        de.put("main.disabled.servermode", "§8Servermodus deaktiviert");

        de.put("admin.mode.title", "EconomyMC Adminmodus");
        de.put("admin.jobs", "Jobs");
        de.put("admin.checks", "Checks");
        de.put("admin.shop", "Shop");
        de.put("admin.plot_market", "Grundstücksmarkt");
        de.put("admin.server_mode", "Servermodus");
        de.put("admin.min_tax", "Mindeststeuer");
        de.put("admin.min_overdue", "Mindest-Überzugsstrafe");
        de.put("admin.min_cancel", "Mindest-Abbruchstrafe");
        de.put("admin.language", "Sprache");
        de.put("admin.language.previous", "§eVorherige Sprache");
        de.put("admin.language.next", "§eNächste Sprache");
        de.put("admin.language.toggle", "§eSprache wechseln");
        de.put("admin.on", "AN");
        de.put("admin.off", "AUS");
        de.put("admin.manual", "Manuell");

        de.put("plots.menu.title", "EconomyMC Grundstücke");
        de.put("plots.position.capital", "§6Aktuelle Position: Hauptstadt-Zone");
        de.put("plots.position.normal", "§7Aktuelle Position: Normale Zone");
        de.put("plots.buy.normal", "§eNormale Claim-Credits kaufen");
        de.put("plots.buy.capital", "§6Hauptstadt-Claim-Credits kaufen");
        de.put("plots.create.sale", "§aVerkaufsangebot erstellen");
        de.put("plots.market", "§3Marktangebote");
        de.put("plots.mine", "§bMeine Grundstücke");
        de.put("plots.sales", "§dMeine Verkäufe");
        de.put("plots.history", "§aVerlauf öffnen");
        de.put("plots.buy.normal.fail", "§cDu hast nicht genug Geld für einen normalen Claim-Credit.");
        de.put("plots.buy.normal.ok", "§a1 normaler Claim-Credit gekauft.");
        de.put("plots.buy.capital.fail", "§cDu hast nicht genug Geld für einen Hauptstadt-Claim-Credit.");
        de.put("plots.buy.capital.ok", "§a1 Hauptstadt-Claim-Credit gekauft.");

        de.put("market.menu.title", "EconomyMC Markt");
        de.put("market.back", "§cZurück");

        de.put("myplots.menu.title", "Meine Grundstücke");
        de.put("myplots.info", "§7Klicke ein Grundstück an, um einen Verkaufsentwurf zu erstellen");
        de.put("myplots.already_listed", "§cDieses Grundstück ist bereits gelistet.");
        de.put("myplots.already_draft", "§cFür dieses Grundstück gibt es schon einen Entwurf.");
        de.put("myplots.edit_later", "Später bearbeiten");

        de.put("mysales.menu.title", "Meine Verkäufe");

        de.put("listing.menu.title", "EconomyMC Angebot");
        de.put("listing.missing", "§cAngebot existiert nicht mehr");
        de.put("listing.buy", "§aKaufen");
        de.put("listing.buy.own", "§cDu kannst dein eigenes Angebot nicht kaufen.");
        de.put("listing.not.enough", "§cDu hast nicht genug Geld.");
        de.put("listing.not.exists", "§cAngebot existiert nicht mehr.");
        de.put("listing.price", "§6Preis: $%d");
        de.put("listing.description", "§7Beschreibung: %s");
        de.put("listing.location", "§7Ort: %s");
        de.put("listing.building", "§7Bebaut: %s");
        de.put("listing.reason", "§7Preisbegründung: %s");
        de.put("listing.chunks", "§7Chunks: %d");

        de.put("sale.menu.title", "EconomyMC Verkaufsangebot erstellen");
        de.put("sale.no_draft", "§cKein Verkaufsentwurf ausgewählt");
        de.put("sale.plot", "§bGrundstück: ");
        de.put("sale.chunks", " Chunks");
        de.put("sale.set_price", "§ePreis setzen");
        de.put("sale.set_description", "§7Beschreibung setzen");
        de.put("sale.set_built", "§7Bebauung setzen");
        de.put("sale.set_justification", "§7Preisbegründung setzen");
        de.put("sale.negotiable", "§aVerhandelbar");
        de.put("sale.fixed", "§6Festpreis");
        de.put("sale.publish", "§bAngebot veröffentlichen");
        de.put("sale.location", "§7Ort: ");
        de.put("sale.clear_draft", "§cEntwurf löschen");
        de.put("sale.already_listed", "§cDieses Grundstück ist bereits gelistet.");
        de.put("sale.published", "§aAngebot veröffentlicht.");
        de.put("sale.cleared", "§aVerkaufsentwurf gelöscht.");
        de.put("sale.selected_capital", "§6Ausgewähltes Hauptstadt-Grundstück");
        de.put("sale.selected_plot", "§7Ausgewähltes Grundstück");

        de.put("shop.menu.title", "EconomyMC Shop");
        de.put("shop.sell.title", "EconomyMC Gegenstand verkaufen");
        de.put("shop.detail.title", "EconomyMC Shop-Details");
        de.put("shop.detail.not_found", "§cAngebot nicht gefunden");
        de.put("shop.detail.info", "§bAngebots-Info");
        de.put("shop.detail.buy", "§aKaufen");
        de.put("shop.bundle", "§dShop-Bündel");
        de.put("shop.base_price", "§6Grundpreis: $");
        de.put("shop.tax", "§cSteuer: $");
        de.put("shop.total", "§aGesamt: $");
        de.put("shop.stacks_inside", "§7Stacks enthalten: ");
        de.put("shop.total_items", "§7Gesamtanzahl Items: ");
        de.put("shop.and_more", "§8...und mehr");
        de.put("shop.sell.set_price", "§ePreis setzen");
        de.put("shop.sell.publish", "§aVeröffentlichen");
        de.put("shop.sell.put_items_first", "§cLege zuerst Items hinein.");
        de.put("shop.sell.published", "§aShop-Angebot veröffentlicht.");
        de.put("shop.input.enter_price", "§eGib jetzt den Shop-Preis im Chat ein.");
        de.put("shop.input.no_draft", "§cKein Shop-Entwurf ausgewählt.");
        de.put("shop.input.price_positive", "§cDer Preis muss über 0 liegen.");
        de.put("shop.input.price_set", "§aShop-Preis gesetzt auf $");
        de.put("shop.input.invalid_number", "§cDas ist keine gültige Zahl.");
        de.put("shop.listing_missing", "Angebot existiert nicht mehr");
        de.put("shop.not_enough_money", "§cDu hast nicht genug Geld.");
        de.put("shop.buy", "§aKaufen");
        de.put("shop.withdraw", "§cAngebot zurückziehen");
        de.put("shop.withdrawn", "§aAngebot zurückgezogen.");

        de.put("jobs.menu.title", "EconomyMC Jobs");
        de.put("jobs.server.title", "EconomyMC Server-Jobs");
        de.put("job.detail.title", "EconomyMC Jobdetails");
        de.put("jobs.add", "§aJob hinzufügen");
        de.put("jobs.create_hint", "§7Erstelle Jobs im richtigen Menü");
        de.put("jobs.status.open", "§aOffen");
        de.put("jobs.status.opens_at", "§eÖffnet ");
        de.put("jobs.status.in_progress", "§6In Bearbeitung: ");
        de.put("jobs.status.completed", "§bErledigt");
        de.put("jobs.status.confirmed", "§aBestätigt");
        de.put("jobs.status.cancelled", "§cAbgebrochen");
        de.put("jobs.status.failed", "§4Gescheitert");
        de.put("jobs.reward", "§6Belohnung: $");
        de.put("jobs.created_by", "§7Erstellt von: ");
        de.put("jobs.description", "§7Beschreibung: ");
        de.put("jobs.due_in", "§7Fällig in: ");
        de.put("jobs.day_suffix", " Tag(e)");
        de.put("jobs.current_payout", "§7Aktuelle Auszahlung: $");
        de.put("jobs.unavailable", "§cJob nicht mehr verfügbar");
        de.put("jobs.accept", "§aJob annehmen");
        de.put("jobs.accept_server", "§aServer-Job annehmen");
        de.put("jobs.available_at", "§eVerfügbar ab ");
        de.put("jobs.withdraw", "§cJob zurückziehen");
        de.put("jobs.mark_completed", "§bAls erledigt markieren");
        de.put("jobs.cancel_job", "§cJob abbrechen");
        de.put("jobs.in_progress_by", "§7In Bearbeitung von ");
        de.put("jobs.confirm_job", "§aJob bestätigen");
        de.put("jobs.waiting_confirmation", "§7Wartet auf Bestätigung");

        de.put("jobs.input.title", "§eGib jetzt den Jobtitel im Chat ein.");
        de.put("jobs.input.server_title", "§eGib jetzt den Server-Jobtitel im Chat ein.");
        de.put("jobs.input.description", "§eGib jetzt die Jobbeschreibung im Chat ein.");
        de.put("jobs.input.reward", "§eGib jetzt die Belohnung im Chat ein.");
        de.put("jobs.input.due_days", "§eGib jetzt die Fälligkeit in vollen Tagen ein.");
        de.put("jobs.input.invalid_number", "§cDas ist keine gültige Zahl.");
        de.put("jobs.input.reward_positive", "§cDie Belohnung muss über 0 liegen.");
        de.put("jobs.input.days_positive", "§cDie Tage müssen über 0 liegen.");
        de.put("jobs.input.treasury_missing", "§cDas Treasury hat nicht genug Geld für diesen Server-Job.");
        de.put("jobs.input.player_missing_money", "§cDu hast nicht genug Geld, um diesen Job zu erstellen.");
        de.put("jobs.input.created", "§aJob erstellt.");

        de.put("jobs.error.accept_yet", "§cDieser Job kann noch nicht angenommen werden.");
        de.put("jobs.error.not_open", "§cDieser Job ist nicht mehr offen.");
        de.put("jobs.error.own_job", "§cDu kannst deinen eigenen Job nicht annehmen.");
        de.put("jobs.error.withdraw", "§cJob konnte nicht zurückgezogen werden.");
        de.put("jobs.error.complete", "§cJob konnte nicht als erledigt markiert werden.");
        de.put("jobs.error.confirm", "§cJob konnte nicht bestätigt werden.");
        de.put("jobs.error.cancel", "§cJob konnte nicht abgebrochen werden.");

        de.put("jobs.msg.accepted", "§aDu hast den Job angenommen.");
        de.put("jobs.msg.accepted_server", "§aDu hast den Server-Job angenommen.");
        de.put("jobs.msg.withdrawn", "§aJob zurückgezogen.");
        de.put("jobs.msg.withdrawn_server", "§aServer-Job zurückgezogen.");
        de.put("jobs.msg.completed", "§aJob als erledigt markiert.");
        de.put("jobs.msg.confirmed", "§aJob bestätigt.");
        de.put("jobs.msg.cancelled_penalty", "§cJob abgebrochen. Strafe: $");

        de.put("checks.menu.title", "EconomyMC Checks");
        de.put("check.redeem.title", "EconomyMC Check einlösen");
        de.put("checks.create", "§aCheck erstellen");
        de.put("checks.creator", "§eErsteller: ");
        de.put("checks.amount", "§6Betrag: $");
        de.put("checks.redeem", "§aEinlösen");
        de.put("checks.redeemed", "§7Bereits eingelöst");
        de.put("checks.not_found", "§cCheck nicht gefunden");
        de.put("checks.no_longer", "§cDieser Check kann nicht mehr eingelöst werden.");
        de.put("checks.entry", "%sCheck $%d - %s");

        de.put("checks.input.amount", "§eGib jetzt den Check-Betrag im Chat ein.");
        de.put("checks.input.code", "§eGib jetzt den Check-Code im Chat ein.");
        de.put("checks.input.invalid_number", "§cDas ist keine gültige Zahl.");
        de.put("checks.input.amount_positive", "§cDer Betrag muss über 0 liegen.");
        de.put("checks.input.not_enough", "§cDu hast nicht genug Geld.");
        de.put("checks.input.created", "§aCheck erstellt.");
        de.put("checks.input.invalid_code", "§cUngültiger Code oder Check bereits eingelöst.");
        de.put("checks.input.redeemed_success", "§aCheck erfolgreich eingelöst.");

        de.put("history.title", "EconomyMC Verlauf");
        de.put("history.empty", "§7Noch keine Einträge vorhanden.");
        de.put("history.mine", "§bMein Verlauf");
        de.put("history.treasury", "§6Treasury-Verlauf");
        de.put("history.open", "§aVerlauf öffnen");
        de.put("history.pay.sent", "§aÜberweisung an %s: $%d");
        de.put("history.pay.received", "§aÜberweisung von %s: $%d");
        de.put("history.daily", "§eTägliche Belohnung: $%d");

        de.put("bank.title", "EconomyMC Bank");
        de.put("bank.loan_id", "Kredit-ID");
        de.put("bank.invalid_target", "§cUnbekannter Zielspieler.");
        de.put("bank.not_enough_money", "§cDu hast nicht genug Geld.");
        de.put("bank.not_found", "§cKredit nicht gefunden.");
        de.put("bank.request.created", "§aKreditanfrage erstellt.");
        de.put("bank.offer.created", "§aKreditangebot erstellt.");
        de.put("bank.accepted", "§aKredit angenommen.");
        de.put("bank.repaid", "§aKredit zurückgezahlt.");
        de.put("bank.target.server", "Server");
        de.put("bank.target.player", "Spieler");
        de.put("bank.target.all", "Alle Spieler");
        de.put("bank.command.request", "Kreditanfrage erstellen");
        de.put("bank.command.offer", "Kreditangebot erstellen");
        de.put("bank.command.accept", "Kredit annehmen");
        de.put("bank.command.repay", "Kredit zurückzahlen");
        de.put("bank.command.list", "Offene Kredite");
        de.put("bank.detail.title", "EconomyMC Kreditdetails");
        de.put("bank.detail.info_hint", "§7Öffne einen Kredit für Details");
        de.put("bank.detail.borrower", "§7Kreditnehmer: ");
        de.put("bank.detail.lender", "§7Kreditgeber: ");
        de.put("bank.detail.amount", "§6Betrag: $");
        de.put("bank.detail.status", "§7Status: ");

        de.put("pay.menu.title", "EconomyMC Bezahlen");
        de.put("pay.menu.player", "§eAn %s zahlen");
        de.put("pay.menu.info", "§7Spieler auswählen");
        de.put("pay.menu.enter_amount", "§eGib jetzt den Betrag für %s im Chat ein.");
        de.put("pay.invalid_number", "§cDas ist kein gültiger Betrag.");
        de.put("pay.target_offline", "§cDieser Spieler ist nicht mehr online.");
        de.put("pay.known_or_treasury", "§cNur bekannte Spieler oder das Treasury können Geld erhalten.");
        de.put("pay.self", "§cDu kannst dir nicht selbst Geld senden.");
        de.put("pay.not_enough", "§cDu hast nicht genug Geld.");
        de.put("pay.sent", "§aDu hast $%d an %s bezahlt.");
        de.put("pay.received", "§aDu hast $%d von %s erhalten.");

        de.put("daily.already", "§cDaily für heute schon abgeholt. Komm in %dh %dm zurück.");
        de.put("daily.claimed", "§aDu hast dein tägliches $100 abgeholt.");

        de.put("server.mode.title", "EconomyMC Servermodus");
        de.put("server.tax_minus", "§cSteuer -1%");
        de.put("server.tax_rate", "§7Steuersatz: ");
        de.put("server.tax_plus", "§aSteuer +1%");
        de.put("server.auto_tax", "Automatische Steuer");
        de.put("server.overdue_minus", "§cÜberzug -1%");
        de.put("server.overdue_penalty", "§7Überzugsgebühr: ");
        de.put("server.overdue_plus", "§aÜberzug +1%");
        de.put("server.cancel_minus", "§cAbbruch -1%");
        de.put("server.cancel_penalty", "§7Abbruchgebühr: ");
        de.put("server.cancel_plus", "§aAbbruch +1%");
        de.put("server.days_minus", "§cTage -1");
        de.put("server.max_overdue_days", "§7Max. Überzugstage: ");
        de.put("server.days_plus", "§aTage +1");
        de.put("server.start_hour_minus", "§cStartstunde -1");
        de.put("server.job_open_hour", "§7Job-Startstunde: ");
        de.put("server.start_hour_plus", "§aStartstunde +1");
        de.put("server.create_job", "§aServer-Job erstellen");
        de.put("server.open_jobs", "§bServer-Jobs öffnen");
        de.put("server.treasury_balance", "§6Treasury: $");

        LANG.put("de_de", de);

        Map<String, String> pl = new HashMap<>(en);
        pl.put("common.close", "§cZamknij");
        pl.put("common.back", "§cPowrót");
        pl.put("common.next", "§7Następna strona");
        pl.put("common.previous", "§7Poprzednia strona");
        pl.put("common.page", "§7Strona ");
        pl.put("menu.player.balance", "§6Stan konta: $%d");
        pl.put("menu.player.normal", "§7Zwykłe kredyty: %d");
        pl.put("menu.player.capital", "§7Kredyty stolicy: %d");
        pl.put("main.plots", "§aDziałki");
        pl.put("main.shop", "§eSklep");
        pl.put("main.jobs", "§bZadania");
        pl.put("main.checks", "§dCzeki");
        pl.put("main.bank", "§6Bank");
        pl.put("main.history", "§7Historia");
        pl.put("main.daily", "§aNagroda dzienna");
        pl.put("main.pay", "§6Płać");
        pl.put("main.servermode", "§cTryb serwera");
        pl.put("main.servermode.disabled", "§8Tryb serwera wyłączony");
        pl.put("main.adminmode", "§4Tryb administratora");
        pl.put("plots.menu.title", "EconomyMC Działki");
        pl.put("plots.position.capital", "§6Aktualna pozycja: Strefa stolicy");
        pl.put("plots.position.normal", "§7Aktualna pozycja: Zwykła strefa");
        pl.put("plots.buy.normal", "§eKup zwykłe kredyty działek");
        pl.put("plots.buy.capital", "§6Kup kredyty działek stolicy");
        pl.put("plots.market", "§3Oferty rynku");
        pl.put("plots.mine", "§bMoje działki");
        pl.put("plots.sales", "§dMoje sprzedaże");
        pl.put("plots.create.sale", "§aUtwórz ofertę sprzedaży");
        pl.put("history.mine", "§bMoja historia");
        pl.put("history.treasury", "§6Historia skarbca");
        pl.put("history.open", "§aOtwórz historię");
        pl.put("admin.mode.title", "EconomyMC Tryb administratora");
        pl.put("admin.jobs", "Zadania");
        pl.put("admin.checks", "Czeki");
        pl.put("admin.shop", "Sklep");
        pl.put("admin.plot_market", "Rynek działek");
        pl.put("admin.server_mode", "Tryb serwera");
        pl.put("admin.language", "Język");
        pl.put("admin.language.previous", "§ePoprzedni język");
        pl.put("admin.language.next", "§eNastępny język");
        pl.put("admin.language.toggle", "§eZmień język");
        pl.put("admin.on", "WŁ");
        pl.put("admin.off", "WYŁ");
        pl.put("jobs.menu.title", "EconomyMC Zadania");
        pl.put("checks.menu.title", "EconomyMC Czeki");
        pl.put("checks.create", "§aUtwórz czek");
        pl.put("checks.creator", "§eTwórca: ");
        pl.put("checks.amount", "§6Kwota: $");
        pl.put("checks.redeem", "§aZrealizuj");
        pl.put("checks.redeemed", "§7Już zrealizowano");
        pl.put("history.title", "EconomyMC Historia");
        pl.put("bank.title", "EconomyMC Bank");
        pl.put("pay.menu.title", "EconomyMC Płatność");
        pl.put("pay.menu.info", "§7Wybierz gracza");
        pl.put("pay.menu.player", "§eZapłać %s");
        pl.put("pay.menu.enter_amount", "§eWpisz teraz kwotę dla %s na czacie.");
        pl.put("jobs.input.title", "§eWpisz teraz tytuł zadania na czacie.");
        pl.put("checks.input.amount", "§eWpisz teraz kwotę czeku na czacie.");
        pl.put("server.mode.title", "EconomyMC Tryb serwera");
        pl.put("server.tax_minus", "§cPodatek -1%");
        pl.put("server.tax_rate", "§7Stawka podatku: ");
        pl.put("server.tax_plus", "§aPodatek +1%");
        pl.put("server.auto_tax", "Automatyczny podatek");
        pl.put("server.overdue_minus", "§cKara -1%");
        pl.put("server.overdue_penalty", "§7Kara za spóźnienie: ");
        pl.put("server.overdue_plus", "§aKara +1%");
        pl.put("server.cancel_minus", "§cAnulowanie -1%");
        pl.put("server.cancel_penalty", "§7Kara za anulowanie: ");
        pl.put("server.cancel_plus", "§aAnulowanie +1%");
        pl.put("server.days_minus", "§cDni -1");
        pl.put("server.max_overdue_days", "§7Maks. dni spóźnienia: ");
        pl.put("server.days_plus", "§aDni +1");
        pl.put("server.start_hour_minus", "§cGodzina -1");
        pl.put("server.job_open_hour", "§7Godzina otwarcia jobów: ");
        pl.put("server.start_hour_plus", "§aGodzina +1");
        pl.put("server.create_job", "§aUtwórz serwerowe zadanie");
        pl.put("server.open_jobs", "§bOtwórz zadania serwera");
        pl.put("server.treasury_balance", "§6Skarbiec: $");
        LANG.put("pl_pl", pl);

        Map<String, String> fr = new HashMap<>(en);
        fr.put("common.close", "§cFermer");
        fr.put("common.back", "§cRetour");
        fr.put("common.next", "§7Page suivante");
        fr.put("common.previous", "§7Page précédente");
        fr.put("common.page", "§7Page ");
        fr.put("menu.player.balance", "§6Solde: $%d");
        fr.put("menu.player.normal", "§7Crédits normaux: %d");
        fr.put("menu.player.capital", "§7Crédits capitale: %d");
        fr.put("main.plots", "§aParcelles");
        fr.put("main.shop", "§eBoutique");
        fr.put("main.jobs", "§bJobs");
        fr.put("main.checks", "§dChèques");
        fr.put("main.bank", "§6Banque");
        fr.put("main.history", "§7Historique");
        fr.put("main.daily", "§aRécompense quotidienne");
        fr.put("main.pay", "§6Payer");
        fr.put("main.servermode", "§cMode serveur");
        fr.put("main.servermode.disabled", "§8Mode serveur désactivé");
        fr.put("main.adminmode", "§4Mode admin");
        fr.put("plots.menu.title", "EconomyMC Parcelles");
        fr.put("plots.position.capital", "§6Position actuelle: zone capitale");
        fr.put("plots.position.normal", "§7Position actuelle: zone normale");
        fr.put("plots.buy.normal", "§eAcheter des crédits normaux");
        fr.put("plots.buy.capital", "§6Acheter des crédits capitale");
        fr.put("plots.market", "§3Offres du marché");
        fr.put("plots.mine", "§bMes parcelles");
        fr.put("plots.sales", "§dMes ventes");
        fr.put("plots.create.sale", "§aCréer une offre de vente");
        fr.put("history.mine", "§bMon historique");
        fr.put("history.treasury", "§6Historique du trésor");
        fr.put("history.open", "§aOuvrir l'historique");
        fr.put("admin.mode.title", "EconomyMC Mode admin");
        fr.put("admin.jobs", "Jobs");
        fr.put("admin.checks", "Chèques");
        fr.put("admin.shop", "Boutique");
        fr.put("admin.plot_market", "Marché des parcelles");
        fr.put("admin.server_mode", "Mode serveur");
        fr.put("admin.language", "Langue");
        fr.put("admin.language.previous", "§eLangue précédente");
        fr.put("admin.language.next", "§eLangue suivante");
        fr.put("admin.language.toggle", "§eChanger la langue");
        fr.put("admin.on", "ACTIF");
        fr.put("admin.off", "INACTIF");
        fr.put("jobs.menu.title", "EconomyMC Jobs");
        fr.put("checks.menu.title", "EconomyMC Chèques");
        fr.put("checks.create", "§aCréer un chèque");
        fr.put("checks.creator", "§eCréateur: ");
        fr.put("checks.amount", "§6Montant: $");
        fr.put("checks.redeem", "§aEncaisser");
        fr.put("checks.redeemed", "§7Déjà encaissé");
        fr.put("history.title", "EconomyMC Historique");
        fr.put("bank.title", "EconomyMC Banque");
        fr.put("pay.menu.title", "EconomyMC Paiement");
        fr.put("pay.menu.info", "§7Sélectionner un joueur");
        fr.put("pay.menu.player", "§ePayer %s");
        fr.put("pay.menu.enter_amount", "§eEntrez maintenant le montant pour %s dans le chat.");
        fr.put("jobs.input.title", "§eEntrez maintenant le titre du job dans le chat.");
        fr.put("checks.input.amount", "§eEntrez maintenant le montant du chèque dans le chat.");
        fr.put("server.mode.title", "EconomyMC Mode serveur");
        fr.put("server.tax_minus", "§cTaxe -1%");
        fr.put("server.tax_rate", "§7Taux de taxe: ");
        fr.put("server.tax_plus", "§aTaxe +1%");
        fr.put("server.auto_tax", "Taxe automatique");
        fr.put("server.overdue_minus", "§cRetard -1%");
        fr.put("server.overdue_penalty", "§7Pénalité de retard: ");
        fr.put("server.overdue_plus", "§aRetard +1%");
        fr.put("server.cancel_minus", "§cAnnulation -1%");
        fr.put("server.cancel_penalty", "§7Pénalité d'annulation: ");
        fr.put("server.cancel_plus", "§aAnnulation +1%");
        fr.put("server.days_minus", "§cJours -1");
        fr.put("server.max_overdue_days", "§7Jours max de retard: ");
        fr.put("server.days_plus", "§aJours +1");
        fr.put("server.start_hour_minus", "§cHeure -1");
        fr.put("server.job_open_hour", "§7Heure d'ouverture des jobs: ");
        fr.put("server.start_hour_plus", "§aHeure +1");
        fr.put("server.create_job", "§aCréer un job serveur");
        fr.put("server.open_jobs", "§bOuvrir les jobs serveur");
        fr.put("server.treasury_balance", "§6Trésor: $");
        LANG.put("fr_fr", fr);

        Map<String, String> es = new HashMap<>(en);
        es.put("common.close", "§cCerrar");
        es.put("common.back", "§cAtrás");
        es.put("common.next", "§7Página siguiente");
        es.put("common.previous", "§7Página anterior");
        es.put("common.page", "§7Página ");
        es.put("menu.player.balance", "§6Saldo: $%d");
        es.put("menu.player.normal", "§7Créditos normales: %d");
        es.put("menu.player.capital", "§7Créditos capital: %d");
        es.put("main.plots", "§aParcelas");
        es.put("main.shop", "§eTienda");
        es.put("main.jobs", "§bTrabajos");
        es.put("main.checks", "§dCheques");
        es.put("main.bank", "§6Banco");
        es.put("main.history", "§7Historial");
        es.put("main.daily", "§aRecompensa diaria");
        es.put("main.pay", "§6Pagar");
        es.put("main.servermode", "§cModo servidor");
        es.put("main.servermode.disabled", "§8Modo servidor desactivado");
        es.put("main.adminmode", "§4Modo admin");
        es.put("plots.menu.title", "EconomyMC Parcelas");
        es.put("plots.position.capital", "§6Posición actual: zona capital");
        es.put("plots.position.normal", "§7Posición actual: zona normal");
        es.put("plots.buy.normal", "§eComprar créditos normales");
        es.put("plots.buy.capital", "§6Comprar créditos capital");
        es.put("plots.market", "§3Ofertas del mercado");
        es.put("plots.mine", "§bMis parcelas");
        es.put("plots.sales", "§dMis ventas");
        es.put("plots.create.sale", "§aCrear oferta de venta");
        es.put("history.mine", "§bMi historial");
        es.put("history.treasury", "§6Historial del tesoro");
        es.put("history.open", "§aAbrir historial");
        es.put("admin.mode.title", "EconomyMC Modo admin");
        es.put("admin.jobs", "Trabajos");
        es.put("admin.checks", "Cheques");
        es.put("admin.shop", "Tienda");
        es.put("admin.plot_market", "Mercado de parcelas");
        es.put("admin.server_mode", "Modo servidor");
        es.put("admin.language", "Idioma");
        es.put("admin.language.previous", "§eIdioma anterior");
        es.put("admin.language.next", "§eIdioma siguiente");
        es.put("admin.language.toggle", "§eCambiar idioma");
        es.put("admin.on", "ENC");
        es.put("admin.off", "APAG");
        es.put("jobs.menu.title", "EconomyMC Trabajos");
        es.put("checks.menu.title", "EconomyMC Cheques");
        es.put("checks.create", "§aCrear cheque");
        es.put("checks.creator", "§eCreador: ");
        es.put("checks.amount", "§6Cantidad: $");
        es.put("checks.redeem", "§aCanjear");
        es.put("checks.redeemed", "§7Ya canjeado");
        es.put("history.title", "EconomyMC Historial");
        es.put("bank.title", "EconomyMC Banco");
        es.put("pay.menu.title", "EconomyMC Pago");
        es.put("pay.menu.info", "§7Seleccionar jugador");
        es.put("pay.menu.player", "§ePagar a %s");
        es.put("pay.menu.enter_amount", "§eEscribe ahora la cantidad para %s en el chat.");
        es.put("jobs.input.title", "§eEscribe ahora el título del trabajo en el chat.");
        es.put("checks.input.amount", "§eEscribe ahora la cantidad del cheque en el chat.");
        es.put("server.mode.title", "EconomyMC Modo servidor");
        es.put("server.tax_minus", "§cImpuesto -1%");
        es.put("server.tax_rate", "§7Tasa de impuesto: ");
        es.put("server.tax_plus", "§aImpuesto +1%");
        es.put("server.auto_tax", "Impuesto automático");
        es.put("server.overdue_minus", "§cRetraso -1%");
        es.put("server.overdue_penalty", "§7Penalización por retraso: ");
        es.put("server.overdue_plus", "§aRetraso +1%");
        es.put("server.cancel_minus", "§cCancelación -1%");
        es.put("server.cancel_penalty", "§7Penalización por cancelación: ");
        es.put("server.cancel_plus", "§aCancelación +1%");
        es.put("server.days_minus", "§cDías -1");
        es.put("server.max_overdue_days", "§7Máx. días de retraso: ");
        es.put("server.days_plus", "§aDías +1");
        es.put("server.start_hour_minus", "§cHora -1");
        es.put("server.job_open_hour", "§7Hora de apertura de trabajos: ");
        es.put("server.start_hour_plus", "§aHora +1");
        es.put("server.create_job", "§aCrear trabajo del servidor");
        es.put("server.open_jobs", "§bAbrir trabajos del servidor");
        es.put("server.treasury_balance", "§6Tesoro: $");
        LANG.put("es_es", es);

        Map<String, String> pt = new HashMap<>(en);
        pt.put("common.close", "§cFechar");
        pt.put("common.back", "§cVoltar");
        pt.put("common.next", "§7Próxima página");
        pt.put("common.previous", "§7Página anterior");
        pt.put("common.page", "§7Página ");
        pt.put("menu.player.balance", "§6Saldo: $%d");
        pt.put("menu.player.normal", "§7Créditos normais: %d");
        pt.put("menu.player.capital", "§7Créditos da capital: %d");
        pt.put("main.plots", "§aTerrenos");
        pt.put("main.shop", "§eLoja");
        pt.put("main.jobs", "§bTrabalhos");
        pt.put("main.checks", "§dCheques");
        pt.put("main.bank", "§6Banco");
        pt.put("main.history", "§7Histórico");
        pt.put("main.daily", "§aRecompensa diária");
        pt.put("main.pay", "§6Pagar");
        pt.put("main.servermode", "§cModo servidor");
        pt.put("main.servermode.disabled", "§8Modo servidor desativado");
        pt.put("main.adminmode", "§4Modo admin");
        pt.put("plots.menu.title", "EconomyMC Terrenos");
        pt.put("plots.position.capital", "§6Posição atual: zona capital");
        pt.put("plots.position.normal", "§7Posição atual: zona normal");
        pt.put("plots.buy.normal", "§eComprar créditos normais");
        pt.put("plots.buy.capital", "§6Comprar créditos capital");
        pt.put("plots.market", "§3Ofertas do mercado");
        pt.put("plots.mine", "§bMeus terrenos");
        pt.put("plots.sales", "§dMinhas vendas");
        pt.put("plots.create.sale", "§aCriar oferta de venda");
        pt.put("history.mine", "§bMeu histórico");
        pt.put("history.treasury", "§6Histórico do tesouro");
        pt.put("history.open", "§aAbrir histórico");
        pt.put("admin.mode.title", "EconomyMC Modo admin");
        pt.put("admin.jobs", "Trabalhos");
        pt.put("admin.checks", "Cheques");
        pt.put("admin.shop", "Loja");
        pt.put("admin.plot_market", "Mercado de terrenos");
        pt.put("admin.server_mode", "Modo servidor");
        pt.put("admin.language", "Idioma");
        pt.put("admin.language.previous", "§eIdioma anterior");
        pt.put("admin.language.next", "§ePróximo idioma");
        pt.put("admin.language.toggle", "§eMudar idioma");
        pt.put("admin.on", "LIG");
        pt.put("admin.off", "DESL");
        pt.put("jobs.menu.title", "EconomyMC Trabalhos");
        pt.put("checks.menu.title", "EconomyMC Cheques");
        pt.put("checks.create", "§aCriar cheque");
        pt.put("checks.creator", "§eCriador: ");
        pt.put("checks.amount", "§6Valor: $");
        pt.put("checks.redeem", "§aResgatar");
        pt.put("checks.redeemed", "§7Já resgatado");
        pt.put("history.title", "EconomyMC Histórico");
        pt.put("bank.title", "EconomyMC Banco");
        pt.put("pay.menu.title", "EconomyMC Pagamento");
        pt.put("pay.menu.info", "§7Selecionar jogador");
        pt.put("pay.menu.player", "§ePagar %s");
        pt.put("pay.menu.enter_amount", "§eDigite agora o valor para %s no chat.");
        pt.put("jobs.input.title", "§eDigite agora o título do trabalho no chat.");
        pt.put("checks.input.amount", "§eDigite agora o valor do cheque no chat.");
        pt.put("server.mode.title", "EconomyMC Modo servidor");
        pt.put("server.tax_minus", "§cImposto -1%");
        pt.put("server.tax_rate", "§7Taxa de imposto: ");
        pt.put("server.tax_plus", "§aImposto +1%");
        pt.put("server.auto_tax", "Imposto automático");
        pt.put("server.overdue_minus", "§cAtraso -1%");
        pt.put("server.overdue_penalty", "§7Multa por atraso: ");
        pt.put("server.overdue_plus", "§aAtraso +1%");
        pt.put("server.cancel_minus", "§cCancelamento -1%");
        pt.put("server.cancel_penalty", "§7Multa por cancelamento: ");
        pt.put("server.cancel_plus", "§aCancelamento +1%");
        pt.put("server.days_minus", "§cDias -1");
        pt.put("server.max_overdue_days", "§7Máx. dias de atraso: ");
        pt.put("server.days_plus", "§aDias +1");
        pt.put("server.start_hour_minus", "§cHora -1");
        pt.put("server.job_open_hour", "§7Hora de abertura dos trabalhos: ");
        pt.put("server.start_hour_plus", "§aHora +1");
        pt.put("server.create_job", "§aCriar trabalho do servidor");
        pt.put("server.open_jobs", "§bAbrir trabalhos do servidor");
        pt.put("server.treasury_balance", "§6Tesouro: $");
        LANG.put("pt_br", pt);

        Map<String, String> ru = new HashMap<>(en);
        ru.put("common.close", "§cЗакрыть");
        ru.put("common.back", "§cНазад");
        ru.put("common.next", "§7Следующая страница");
        ru.put("common.previous", "§7Предыдущая страница");
        ru.put("common.page", "§7Страница ");
        ru.put("menu.player.balance", "§6Баланс: $%d");
        ru.put("menu.player.normal", "§7Обычные кредиты: %d");
        ru.put("menu.player.capital", "§7Кредиты столицы: %d");
        ru.put("main.plots", "§aУчастки");
        ru.put("main.shop", "§eМагазин");
        ru.put("main.jobs", "§bЗадания");
        ru.put("main.checks", "§dЧеки");
        ru.put("main.bank", "§6Банк");
        ru.put("main.history", "§7История");
        ru.put("main.daily", "§aЕжедневная награда");
        ru.put("main.pay", "§6Оплатить");
        ru.put("main.servermode", "§cРежим сервера");
        ru.put("main.servermode.disabled", "§8Режим сервера отключён");
        ru.put("main.adminmode", "§4Режим администратора");
        ru.put("plots.menu.title", "EconomyMC Участки");
        ru.put("plots.position.capital", "§6Текущая позиция: столица");
        ru.put("plots.position.normal", "§7Текущая позиция: обычная зона");
        ru.put("plots.buy.normal", "§eКупить обычные кредиты участков");
        ru.put("plots.buy.capital", "§6Купить кредиты столицы");
        ru.put("plots.market", "§3Рыночные предложения");
        ru.put("plots.mine", "§bМои участки");
        ru.put("plots.sales", "§dМои продажи");
        ru.put("plots.create.sale", "§aСоздать предложение продажи");
        ru.put("history.mine", "§bМоя история");
        ru.put("history.treasury", "§6История казны");
        ru.put("history.open", "§aОткрыть историю");
        ru.put("admin.mode.title", "EconomyMC Режим администратора");
        ru.put("admin.jobs", "Задания");
        ru.put("admin.checks", "Чеки");
        ru.put("admin.shop", "Магазин");
        ru.put("admin.plot_market", "Рынок участков");
        ru.put("admin.server_mode", "Режим сервера");
        ru.put("admin.language", "Язык");
        ru.put("admin.language.previous", "§eПредыдущий язык");
        ru.put("admin.language.next", "§eСледующий язык");
        ru.put("admin.language.toggle", "§eСменить язык");
        ru.put("admin.on", "ВКЛ");
        ru.put("admin.off", "ВЫКЛ");
        ru.put("jobs.menu.title", "EconomyMC Задания");
        ru.put("checks.menu.title", "EconomyMC Чеки");
        ru.put("checks.create", "§aСоздать чек");
        ru.put("checks.creator", "§eСоздатель: ");
        ru.put("checks.amount", "§6Сумма: $");
        ru.put("checks.redeem", "§aПогасить");
        ru.put("checks.redeemed", "§7Уже погашен");
        ru.put("history.title", "EconomyMC История");
        ru.put("bank.title", "EconomyMC Банк");
        ru.put("pay.menu.title", "EconomyMC Платёж");
        ru.put("pay.menu.info", "§7Выберите игрока");
        ru.put("pay.menu.player", "§eЗаплатить %s");
        ru.put("pay.menu.enter_amount", "§eВведите сумму для %s в чат.");
        ru.put("jobs.input.title", "§eВведите название задания в чат.");
        ru.put("checks.input.amount", "§eВведите сумму чека в чат.");
        ru.put("server.mode.title", "EconomyMC Режим сервера");
        ru.put("server.tax_minus", "§cНалог -1%");
        ru.put("server.tax_rate", "§7Ставка налога: ");
        ru.put("server.tax_plus", "§aНалог +1%");
        ru.put("server.auto_tax", "Автоналог");
        ru.put("server.overdue_minus", "§cПросрочка -1%");
        ru.put("server.overdue_penalty", "§7Штраф за просрочку: ");
        ru.put("server.overdue_plus", "§aПросрочка +1%");
        ru.put("server.cancel_minus", "§cОтмена -1%");
        ru.put("server.cancel_penalty", "§7Штраф за отмену: ");
        ru.put("server.cancel_plus", "§aОтмена +1%");
        ru.put("server.days_minus", "§cДни -1");
        ru.put("server.max_overdue_days", "§7Макс. дней просрочки: ");
        ru.put("server.days_plus", "§aДни +1");
        ru.put("server.start_hour_minus", "§cЧас -1");
        ru.put("server.job_open_hour", "§7Час открытия работ: ");
        ru.put("server.start_hour_plus", "§aЧас +1");
        ru.put("server.create_job", "§aСоздать серверную работу");
        ru.put("server.open_jobs", "§bОткрыть серверные работы");
        ru.put("server.treasury_balance", "§6Казна: $");
        LANG.put("ru_ru", ru);

        Map<String, String> tr = new HashMap<>(en);
        tr.put("common.close", "§cKapat");
        tr.put("common.back", "§cGeri");
        tr.put("common.next", "§7Sonraki sayfa");
        tr.put("common.previous", "§7Önceki sayfa");
        tr.put("common.page", "§7Sayfa ");
        tr.put("menu.player.balance", "§6Bakiye: $%d");
        tr.put("menu.player.normal", "§7Normal krediler: %d");
        tr.put("menu.player.capital", "§7Başkent kredileri: %d");
        tr.put("main.plots", "§aArsalar");
        tr.put("main.shop", "§eMağaza");
        tr.put("main.jobs", "§bİşler");
        tr.put("main.checks", "§dÇekler");
        tr.put("main.bank", "§6Banka");
        tr.put("main.history", "§7Geçmiş");
        tr.put("main.daily", "§aGünlük ödül");
        tr.put("main.pay", "§6Öde");
        tr.put("main.servermode", "§cSunucu modu");
        tr.put("main.servermode.disabled", "§8Sunucu modu devre dışı");
        tr.put("main.adminmode", "§4Yönetici modu");
        tr.put("plots.menu.title", "EconomyMC Arsalar");
        tr.put("plots.position.capital", "§6Geçerli konum: başkent bölgesi");
        tr.put("plots.position.normal", "§7Geçerli konum: normal bölge");
        tr.put("plots.buy.normal", "§eNormal arsa kredisi al");
        tr.put("plots.buy.capital", "§6Başkent arsa kredisi al");
        tr.put("plots.market", "§3Pazar teklifleri");
        tr.put("plots.mine", "§bArsalarım");
        tr.put("plots.sales", "§dSatışlarım");
        tr.put("plots.create.sale", "§aSatış ilanı oluştur");
        tr.put("history.mine", "§bBenim geçmişim");
        tr.put("history.treasury", "§6Hazine geçmişi");
        tr.put("history.open", "§aGeçmişi aç");
        tr.put("admin.mode.title", "EconomyMC Yönetici modu");
        tr.put("admin.jobs", "İşler");
        tr.put("admin.checks", "Çekler");
        tr.put("admin.shop", "Mağaza");
        tr.put("admin.plot_market", "Arsa pazarı");
        tr.put("admin.server_mode", "Sunucu modu");
        tr.put("admin.language", "Dil");
        tr.put("admin.language.previous", "§eÖnceki dil");
        tr.put("admin.language.next", "§eSonraki dil");
        tr.put("admin.language.toggle", "§eDili değiştir");
        tr.put("admin.on", "AÇIK");
        tr.put("admin.off", "KAPALI");
        tr.put("jobs.menu.title", "EconomyMC İşler");
        tr.put("checks.menu.title", "EconomyMC Çekler");
        tr.put("checks.create", "§aÇek oluştur");
        tr.put("checks.creator", "§eOluşturan: ");
        tr.put("checks.amount", "§6Miktar: $");
        tr.put("checks.redeem", "§aBozdur");
        tr.put("checks.redeemed", "§7Zaten bozduruldu");
        tr.put("history.title", "EconomyMC Geçmiş");
        tr.put("bank.title", "EconomyMC Banka");
        tr.put("pay.menu.title", "EconomyMC Ödeme");
        tr.put("pay.menu.info", "§7Oyuncu seç");
        tr.put("pay.menu.player", "§e%s adlı oyuncuya öde");
        tr.put("pay.menu.enter_amount", "§eŞimdi %s için miktarı sohbete yaz.");
        tr.put("jobs.input.title", "§eŞimdi iş başlığını sohbete yaz.");
        tr.put("checks.input.amount", "§eŞimdi çek miktarını sohbete yaz.");
        tr.put("server.mode.title", "EconomyMC Sunucu modu");
        tr.put("server.tax_minus", "§cVergi -1%");
        tr.put("server.tax_rate", "§7Vergi oranı: ");
        tr.put("server.tax_plus", "§aVergi +1%");
        tr.put("server.auto_tax", "Otomatik vergi");
        tr.put("server.overdue_minus", "§cGecikme -1%");
        tr.put("server.overdue_penalty", "§7Gecikme cezası: ");
        tr.put("server.overdue_plus", "§aGecikme +1%");
        tr.put("server.cancel_minus", "§cİptal -1%");
        tr.put("server.cancel_penalty", "§7İptal cezası: ");
        tr.put("server.cancel_plus", "§aİptal +1%");
        tr.put("server.days_minus", "§cGün -1");
        tr.put("server.max_overdue_days", "§7Maks. gecikme günü: ");
        tr.put("server.days_plus", "§aGün +1");
        tr.put("server.start_hour_minus", "§cSaat -1");
        tr.put("server.job_open_hour", "§7İş açılış saati: ");
        tr.put("server.start_hour_plus", "§aSaat +1");
        tr.put("server.create_job", "§aSunucu işi oluştur");
        tr.put("server.open_jobs", "§bSunucu işlerini aç");
        tr.put("server.treasury_balance", "§6Hazine: $");
        LANG.put("tr_tr", tr);

        Map<String, String> zh = new HashMap<>(en);
        zh.put("common.close", "§c关闭");
        zh.put("common.back", "§c返回");
        zh.put("common.next", "§7下一页");
        zh.put("common.previous", "§7上一页");
        zh.put("common.page", "§7第 ");
        zh.put("menu.player.balance", "§6余额: $%d");
        zh.put("menu.player.normal", "§7普通积分: %d");
        zh.put("menu.player.capital", "§7首都积分: %d");
        zh.put("main.plots", "§a地块");
        zh.put("main.shop", "§e商店");
        zh.put("main.jobs", "§b工作");
        zh.put("main.checks", "§d支票");
        zh.put("main.bank", "§6银行");
        zh.put("main.history", "§7历史");
        zh.put("main.daily", "§a每日奖励");
        zh.put("main.pay", "§6支付");
        zh.put("main.servermode", "§c服务器模式");
        zh.put("main.servermode.disabled", "§8服务器模式已禁用");
        zh.put("main.adminmode", "§4管理模式");
        zh.put("plots.menu.title", "EconomyMC 地块");
        zh.put("plots.position.capital", "§6当前位置: 主城区域");
        zh.put("plots.position.normal", "§7当前位置: 普通区域");
        zh.put("plots.buy.normal", "§e购买普通地块积分");
        zh.put("plots.buy.capital", "§6购买主城地块积分");
        zh.put("plots.market", "§3市场列表");
        zh.put("plots.mine", "§b我的地块");
        zh.put("plots.sales", "§d我的出售");
        zh.put("plots.create.sale", "§a创建出售列表");
        zh.put("history.mine", "§b我的历史");
        zh.put("history.treasury", "§6国库历史");
        zh.put("history.open", "§a打开历史");
        zh.put("admin.mode.title", "EconomyMC 管理模式");
        zh.put("admin.jobs", "工作");
        zh.put("admin.checks", "支票");
        zh.put("admin.shop", "商店");
        zh.put("admin.plot_market", "地块市场");
        zh.put("admin.server_mode", "服务器模式");
        zh.put("admin.language", "语言");
        zh.put("admin.language.previous", "§e上一个语言");
        zh.put("admin.language.next", "§e下一个语言");
        zh.put("admin.language.toggle", "§e切换语言");
        zh.put("admin.on", "开");
        zh.put("admin.off", "关");
        zh.put("jobs.menu.title", "EconomyMC 工作");
        zh.put("checks.menu.title", "EconomyMC 支票");
        zh.put("checks.create", "§a创建支票");
        zh.put("checks.creator", "§e创建者: ");
        zh.put("checks.amount", "§6金额: $");
        zh.put("checks.redeem", "§a兑现");
        zh.put("checks.redeemed", "§7已兑现");
        zh.put("history.title", "EconomyMC 历史");
        zh.put("bank.title", "EconomyMC 银行");
        zh.put("pay.menu.title", "EconomyMC 支付");
        zh.put("pay.menu.info", "§7选择玩家");
        zh.put("pay.menu.player", "§e支付给 %s");
        zh.put("pay.menu.enter_amount", "§e现在请在聊天中输入给 %s 的金额。");
        zh.put("jobs.input.title", "§e现在请在聊天中输入工作标题。");
        zh.put("checks.input.amount", "§e现在请在聊天中输入支票金额。");
        zh.put("server.mode.title", "EconomyMC 服务器模式");
        zh.put("server.tax_minus", "§c税率 -1%");
        zh.put("server.tax_rate", "§7税率: ");
        zh.put("server.tax_plus", "§a税率 +1%");
        zh.put("server.auto_tax", "自动税");
        zh.put("server.overdue_minus", "§c逾期 -1%");
        zh.put("server.overdue_penalty", "§7逾期罚金: ");
        zh.put("server.overdue_plus", "§a逾期 +1%");
        zh.put("server.cancel_minus", "§c取消 -1%");
        zh.put("server.cancel_penalty", "§7取消罚金: ");
        zh.put("server.cancel_plus", "§a取消 +1%");
        zh.put("server.days_minus", "§c天数 -1");
        zh.put("server.max_overdue_days", "§7最大逾期天数: ");
        zh.put("server.days_plus", "§a天数 +1");
        zh.put("server.start_hour_minus", "§c小时 -1");
        zh.put("server.job_open_hour", "§7工作开放时间: ");
        zh.put("server.start_hour_plus", "§a小时 +1");
        zh.put("server.create_job", "§a创建服务器工作");
        zh.put("server.open_jobs", "§b打开服务器工作");
        zh.put("server.treasury_balance", "§6国库: $");
        LANG.put("zh_cn", zh);

        Map<String, String> ja = new HashMap<>(en);
        ja.put("common.close", "§c閉じる");
        ja.put("common.back", "§c戻る");
        ja.put("common.next", "§7次のページ");
        ja.put("common.previous", "§7前のページ");
        ja.put("common.page", "§7ページ ");
        ja.put("menu.player.balance", "§6残高: $%d");
        ja.put("menu.player.normal", "§7通常クレジット: %d");
        ja.put("menu.player.capital", "§7首都クレジット: %d");
        ja.put("main.plots", "§a区画");
        ja.put("main.shop", "§eショップ");
        ja.put("main.jobs", "§bジョブ");
        ja.put("main.checks", "§d小切手");
        ja.put("main.bank", "§6銀行");
        ja.put("main.history", "§7履歴");
        ja.put("main.daily", "§aデイリー報酬");
        ja.put("main.pay", "§6支払う");
        ja.put("main.servermode", "§cサーバーモード");
        ja.put("main.servermode.disabled", "§8サーバーモード無効");
        ja.put("main.adminmode", "§4管理モード");
        ja.put("plots.menu.title", "EconomyMC 区画");
        ja.put("plots.position.capital", "§6現在位置: 首都エリア");
        ja.put("plots.position.normal", "§7現在位置: 通常エリア");
        ja.put("plots.buy.normal", "§e通常区画クレジットを購入");
        ja.put("plots.buy.capital", "§6首都区画クレジットを購入");
        ja.put("plots.market", "§3市場リスト");
        ja.put("plots.mine", "§b自分の区画");
        ja.put("plots.sales", "§d自分の販売");
        ja.put("plots.create.sale", "§a販売リストを作成");
        ja.put("history.mine", "§b自分の履歴");
        ja.put("history.treasury", "§6金庫履歴");
        ja.put("history.open", "§a履歴を開く");
        ja.put("admin.mode.title", "EconomyMC 管理モード");
        ja.put("admin.jobs", "ジョブ");
        ja.put("admin.checks", "小切手");
        ja.put("admin.shop", "ショップ");
        ja.put("admin.plot_market", "区画市場");
        ja.put("admin.server_mode", "サーバーモード");
        ja.put("admin.language", "言語");
        ja.put("admin.language.previous", "§e前の言語");
        ja.put("admin.language.next", "§e次の言語");
        ja.put("admin.language.toggle", "§e言語を変更");
        ja.put("admin.on", "オン");
        ja.put("admin.off", "オフ");
        ja.put("jobs.menu.title", "EconomyMC ジョブ");
        ja.put("checks.menu.title", "EconomyMC 小切手");
        ja.put("checks.create", "§a小切手を作成");
        ja.put("checks.creator", "§e作成者: ");
        ja.put("checks.amount", "§6金額: $");
        ja.put("checks.redeem", "§a換金する");
        ja.put("checks.redeemed", "§7換金済み");
        ja.put("history.title", "EconomyMC 履歴");
        ja.put("bank.title", "EconomyMC 銀行");
        ja.put("pay.menu.title", "EconomyMC 支払い");
        ja.put("pay.menu.info", "§7プレイヤーを選択");
        ja.put("pay.menu.player", "§e%s に支払う");
        ja.put("pay.menu.enter_amount", "§e今すぐ %s への金額をチャットに入力してください。");
        ja.put("jobs.input.title", "§e今すぐチャットにジョブ名を入力してください。");
        ja.put("checks.input.amount", "§e今すぐチャットに小切手金額を入力してください。");
        ja.put("server.mode.title", "EconomyMC サーバーモード");
        ja.put("server.tax_minus", "§c税率 -1%");
        ja.put("server.tax_rate", "§7税率: ");
        ja.put("server.tax_plus", "§a税率 +1%");
        ja.put("server.auto_tax", "自動税");
        ja.put("server.overdue_minus", "§c延滞 -1%");
        ja.put("server.overdue_penalty", "§7延滞料金: ");
        ja.put("server.overdue_plus", "§a延滞 +1%");
        ja.put("server.cancel_minus", "§cキャンセル -1%");
        ja.put("server.cancel_penalty", "§7キャンセル料金: ");
        ja.put("server.cancel_plus", "§aキャンセル +1%");
        ja.put("server.days_minus", "§c日数 -1");
        ja.put("server.max_overdue_days", "§7最大延滞日数: ");
        ja.put("server.days_plus", "§a日数 +1");
        ja.put("server.start_hour_minus", "§c開始時刻 -1");
        ja.put("server.job_open_hour", "§7ジョブ開始時刻: ");
        ja.put("server.start_hour_plus", "§a開始時刻 +1");
        ja.put("server.create_job", "§aサーバージョブを作成");
        ja.put("server.open_jobs", "§bサーバージョブを開く");
        ja.put("server.treasury_balance", "§6金庫: $");
        LANG.put("ja_jp", ja);
    }

    private LanguageManager() {
    }

    public static String tr(String key) {
        return tr(AdminSettingsManager.language(), key);
    }

    public static String tr(String lang, String key) {
        Map<String, String> source = LANG.getOrDefault(lang, LANG.get("en_us"));
        return source.getOrDefault(key, LANG.get("en_us").getOrDefault(key, key));
    }

    public static String format(String key, Object... args) {
        return String.format(tr(key), args);
    }

    public static String currentLanguageLabel() {
        return languageName(AdminSettingsManager.language());
    }

    public static String languageName(String code) {
        return LANGUAGE_NAMES.getOrDefault(code, code);
    }
}