modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="Karl_der_III-creator"
description='''
Economymc is an economy and land-management mod for NeoForge.
It combines plot trading, jobs, treasury management, shop systems,
claim credits, server administration tools, checks, and configurable taxes.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
